In [239]:
import pymysql
import sys
import numpy as np
import pandas as pd
import json
import os
import statsmodels.api as sm
import statsmodels.formula.api as smf
import datetime

conn =pymysql.connect(
    host="fermi-master.c4kp2nxu0eer.ap-northeast-2.rds.amazonaws.com",
    user="admin",
    password="fermi1234",
    db="energy_data",
    charset='utf8'
)
curs=conn.cursor()
sql="""
select smp_price.date, smp_price.total_price as smp_price, oil_price.wti,elec_supply.supply,price_index.korea_producer, price_index.us_producer from smp_price
    inner join oil_price
		on smp_price.date=oil_price.date
	inner join elec_supply
		on smp_price.date=elec_supply.date
	inner join price_index
		on smp_price.date=price_index.date
        """
curs.execute(sql)
array=np.array(curs.fetchall())
data=pd.DataFrame(data=array[:,1:6],index=array[:,0],columns=["smp_price","oil_price","elec_supply","korea_producer","us_producer"])
data.smp_price=data.smp_price*data.korea_producer
data.oil_price=data.oil_price*data.us_producer
data=data.astype(float)

# 회귀분석 모델 만들기 
model=smf.ols(formula = 'smp_price~oil_price+elec_supply', data = data).fit()

def make_scenario(year,scenario):
    curs=conn.cursor()
    fields_sql="SHOW FIELDS FROM `oil_forecast`"
    curs.execute(fields_sql)
    fields=[]
    fields_result=curs.fetchall()
    for i in fields_result: 
        fields.append(i[0])        
    time=pd.period_range(start=datetime.date.today().strftime("%Y-%m-%d"),periods=12*15,freq='M')
    startDate=str(time[0])
    endDate=str(time[len(time)-1])
    main_sql ="SELECT * FROM `oil_forecast` where date>=%s && date<=%s"
    curs=conn.cursor()
    curs.execute(main_sql,(startDate+'-01',endDate+'-01'))
    result=pd.DataFrame(data=np.array(curs.fetchall()),index=time,columns=fields).loc[:,scenario]
    return result

                            OLS Regression Results
==============================================================================
Dep. Variable:              smp_price   R-squared:                       0.422
Model:                            OLS   Adj. R-squared:                  0.416
Method:                 Least Squares   F-statistic:                     65.37
Date:                Mon, 09 Apr 2018   Prob (F-statistic):           4.85e-22
Time:                        14:11:15   Log-Likelihood:                -839.46
No. Observations:                 182   AIC:                             1685.
Df Residuals:                     179   BIC:                             1695.
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [95.0% Conf. Int.]
-------------------------------------------------------------------------------
Intercept      94.4318      9.689      9.747      0.000        75.313   113.550
oil_price       0.5530      0.084      6.617      0.000         0.388     0.718
elec_supply    -1.9895      0.362     -5.503      0.000        -2.703    -1.276
==============================================================================
Omnibus:                       39.388   Durbin-Watson:                   0.324
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               82.107
Skew:                           0.994   Prob(JB):                     1.48e-18
Kurtosis:                       5.621   Cond. No.                         418.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [210]:
import datetime
time=pd.period_range(start=datetime.date.today().strftime("%Y-%m-%d"),periods=12*15,freq='M')
startDate=str(time[0])
endDate=str(time[len(time)-1])
print(startDate+'-01',endDate+'-01')

2018-04-01 2033-03-01

In [238]:


pre_data=make_scenario(15,['WEO_NP','WEO_450'])
pre_data

          WEO_NP  WEO_450
2018-04    62.23    62.23
2018-05  63.0286  62.7429
2018-06  63.8271  63.2557
2018-07  64.6257  63.7686
2018-08  65.4243  64.2814
2018-09  66.2229  64.7943
2018-10  67.0214  65.3071
2018-11    67.82    65.82
2018-12  68.6186  66.3329
2019-01  69.4171  66.8457
2019-02  70.2157  67.3586
2019-03  71.0143  67.8714
2019-04  71.8129  68.3843
2019-05  72.6114  68.8971
2019-06    73.41    69.41
2019-07  74.2086  69.9229
2019-08  75.0071  70.4357
2019-09  75.8057  70.9486
2019-10  76.6043  71.4614
2019-11  77.4029  71.9743
2019-12  78.2014  72.4871
2020-01       79       73
2020-02  79.2667     73.1
2020-03  79.5333     73.2
2020-04     79.8     73.3
2020-05  80.0667     73.4
2020-06  80.3333     73.5
2020-07     80.6     73.6
2020-08  80.8667     73.7
2020-09  81.1333     73.8
...          ...      ...
2030-10  111.975     84.1
2030-11  112.083       84
2030-12  112.192     83.9
2031-01    112.3     83.8
2031-02  112.408     83.7
2031-03  112.517     83.6
2031-04  112.625     83.5
2031-05  112.733     83.4
2031-06  112.842     83.3
2031-07   112.95     83.2
2031-08  113.058     83.1
2031-09  113.167       83
2031-10  113.275     82.9
2031-11  113.383     82.8
2031-12  113.492     82.7
2032-01    113.6     82.6
2032-02  113.708     82.5
2032-03  113.817     82.4
2032-04  113.925     82.3
2032-05  114.033     82.2
2032-06  114.142     82.1
2032-07   114.25       82
2032-08  114.358     81.9
2032-09  114.467     81.8
2032-10  114.575     81.7
2032-11  114.683     81.6
2032-12  114.792     81.5
2033-01    114.9     81.4
2033-02  115.008     81.3
2033-03  115.117     81.2

[180 rows x 2 columns]

In [227]:
sql1 ="SHOW FIELDS FROM `oil_forecast`"
curs=conn.cursor()
curs.execute(sql1)
data=[]
data+['b']
result=curs.fetchall()
for i in result: 
    data.append(i[0])
print(data)

['date', 'WEO_NP', 'WEO_CP', 'WEO_450']

In [226]:
data=['a']
data[1]=['b']
data

IndexError: list assignment index out of range

             WEO_NP      WEO_CP    WEO_450
2018-04   62.230000   62.230000  62.230000
2018-05   63.028571   63.171429  62.742857
2018-06   63.827143   64.112857  63.255714
2018-07   64.625714   65.054286  63.768571
2018-08   65.424286   65.995714  64.281429
2018-09   66.222857   66.937143  64.794286
2018-10   67.021429   67.878571  65.307143
2018-11   67.820000   68.820000  65.820000
2018-12   68.618571   69.761429  66.332857
2019-01   69.417143   70.702857  66.845714
2019-02   70.215714   71.644286  67.358571
2019-03   71.014286   72.585714  67.871429
2019-04   71.812857   73.527143  68.384286
2019-05   72.611429   74.468571  68.897143
2019-06   73.410000   75.410000  69.410000
2019-07   74.208571   76.351429  69.922857
2019-08   75.007143   77.292857  70.435714
2019-09   75.805714   78.234286  70.948571
2019-10   76.604286   79.175714  71.461429
2019-11   77.402857   80.117143  71.974286
2019-12   78.201429   81.058571  72.487143
2020-01   79.000000   82.000000  73.000000
2020-02   79.266667   82.375000  73.100000
2020-03   79.533333   82.750000  73.200000
2020-04   79.800000   83.125000  73.300000
2020-05   80.066667   83.500000  73.400000
2020-06   80.333333   83.875000  73.500000
2020-07   80.600000   84.250000  73.600000
2020-08   80.866667   84.625000  73.700000
2020-09   81.133333   85.000000  73.800000
...             ...         ...        ...
2040-10  124.000000  146.000000  73.000000
2040-11  124.000000  146.000000  73.000000
2040-12  124.000000  146.000000  73.000000
2041-01  124.000000  146.000000  73.000000
2041-02  124.000000  146.000000  73.000000
2041-03  124.000000  146.000000  73.000000
2041-04  124.000000  146.000000  73.000000
2041-05  124.000000  146.000000  73.000000
2041-06  124.000000  146.000000  73.000000
2041-07  124.000000  146.000000  73.000000
2041-08  124.000000  146.000000  73.000000
2041-09  124.000000  146.000000  73.000000
2041-10  124.000000  146.000000  73.000000
2041-11  124.000000  146.000000  73.000000
2041-12  124.000000  146.000000  73.000000
2042-01  124.000000  146.000000  73.000000
2042-02  124.000000  146.000000  73.000000
2042-03  124.000000  146.000000  73.000000
2042-04  124.000000  146.000000  73.000000
2042-05  124.000000  146.000000  73.000000
2042-06  124.000000  146.000000  73.000000
2042-07  124.000000  146.000000  73.000000
2042-08  124.000000  146.000000  73.000000
2042-09  124.000000  146.000000  73.000000
2042-10  124.000000  146.000000  73.000000
2042-11  124.000000  146.000000  73.000000
2042-12  124.000000  146.000000  73.000000
2043-01  124.000000  146.000000  73.000000
2043-02  124.000000  146.000000  73.000000
2043-03  124.000000  146.000000  73.000000

[300 rows x 3 columns]

In [72]:
os.chdir("/Users/youngji/github/data")
writer = pd.ExcelWriter('oil_forcast.xlsx')
WEO1.to_excel(writer,'oil_forcast')
writer.save()